spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: shallowMall-third-party

server:
  port: 30000

logging:
  level:
    com.fyq.shallowMall: debug